---
  - name: APP | Clone project
    git:
      repo: https://github.com/humberthomattar/coinscraper.git
      dest: /home/vagrant/coinscraper/app/
      clone: yes
      update: yes
    become: yes
    become_user: vagrant
  
  - name: Install requirements
    pip: 
      requirements: /home/vagrant/coinscraper/app/requirements.txt
      virtualenv: /home/vagrant/coinscraper/
      virtualenv_python: python3
    become: yes
    become_user: vagrant